export const CONTENT_LIST_REQUEST = 'CONTENT_LIST_REQUEST'
export const CONTENT_LIST_SUCCESS = 'CONTENT_LIST_SUCCESS'
export const CONTENT_LIST_FAIL = 'CONTENT_LIST_FAIL'

export const CONTENT_CATEGORY_REQUEST = 'CONTENT_CATEGORY_REQUEST'
export const CONTENT_CATEGORY_SUCCESS = 'CONTENT_CATEGORY_SUCCESS'
export const CONTENT_CATEGORY_FAIL = 'CONTENT_CATEGORY_FAIL'
