export const CONTENT_LIST_REQUEST = 'CONTENT_LIST_REQUEST'
export const CONTENT_LIST_SUCCESS = 'CONTENT_LIST_SUCCESS'
export const CONTENT_LIST_FAIL = 'CONTENT_LIST_FAIL'

export const CONTENT_CATEGORY_REQUEST = 'CONTENT_CATEGORY_REQUEST'
export const CONTENT_CATEGORY_SUCCESS = 'CONTENT_CATEGORY_SUCCESS'
export const CONTENT_CATEGORY_FAIL = 'CONTENT_CATEGORY_FAIL'

export const CONTENT_DETAIL_REQUEST = 'CONTENT_DETAIL_REQUEST'
export const CONTENT_DETAIL_SUCCESS = 'CONTENT_DETAIL_SUCCESS'
export const CONTENT_DETAIL_FAIL = 'CONTENT_DETAIL_FAIL'

export const CONTENT_COMMENT_REQUEST = 'CONTENT_COMMENT_REQUEST'
export const CONTENT_COMMENT_SUCCESS = 'CONTENT_COMMENT_SUCCESS'
export const CONTENT_COMMENT_FAIL = 'CONTENT_COMMENT_FAIL'

export const CONTENT_POST_REQUEST = 'CONTENT_POST_REQUEST'
export const CONTENT_POST_SUCCESS = 'CONTENT_POST_SUCCESS'
export const CONTENT_POST_FAIL = 'CONTENT_POST_FAIL'

export const CONTENT_DELETE_REQUEST = 'CONTENT_DELETE_REQUEST'
export const CONTENT_DELETE_SUCCESS = 'CONTENT_DELETE_SUCCESS'
export const CONTENT_DELETE_FAIL = 'CONTENT_DELETE_FAIL'
