export const QUESTIONAIRE_POST_REQUEST = 'QUESTIONAIRE_POST_REQUEST'
export const QUESTIONAIRE_POST_SUCCESS = 'QUESTIONAIRE_POST_SUCCESS'
export const QUESTIONAIRE_POST_FAIL = 'QUESTIONAIRE_POST_FAIL'
